import { Course } from "@/types/Types";
import img1 from "@/assets/img-1.jpg";

export const featuredCourses: Course[] = [
   {
      id: "1",
      title: "Complete JavaScript Bootcamp: From Zero to Hero, From Zero to Hero",
      instructor: "John Smith",
      category: { id: "cat1", name: "Web Development" },
      description:
         "Learn JavaScript from scratch and build real-world projects in this comprehensive course.",
      totalPrice: 49.99,
      thumbnail: img1.src,
      rating: 4.8,
      ratingsCount: 42297,
      isBestSeller: true,
      updated: "July 2023",
      progress: 0,
      sections: [
         {
            id: "sec1",
            title: "Basics",
            price: 0,
            lectures: [
               {
                  id: "lec1",
                  title: "Intro to JS",
                  fileType: "video",
                  fileUrl: "https://example.com/video1.mp4",
                  duration: "5:00",
                  isWatched: false,
               },
            ],
         },
      ],
   },
   {
      id: "2",
      title: "Python for Data Science and Machine Learning",
      instructor: "Sarah Johnson",
      category: { id: "cat2", name: "Data Science" },
      description:
         "Master Python for data science, including pandas, numpy, and machine learning basics.",
      totalPrice: 79.99,
      thumbnail: img1.src,
      rating: 4.6,
      ratingsCount: 12345,
      isBestSeller: false,
      updated: "July 2023",
      progress: 0,
      sections: [
         {
            id: "sec2",
            title: "Intro to Python",
            price: 0,
            lectures: [
               {
                  id: "lec2",
                  title: "Python Basics",
                  fileType: "video",
                  fileUrl: "https://example.com/video2.mp4",
                  duration: "7:30",
                  isWatched: false,
               },
            ],
         },
      ],
   },
   {
      id: "3",
      title: "Introduction to Web Development",
      instructor: "Michael Brown",
      category: { id: "cat1", name: "Web Development" },
      description: "A beginner-friendly course covering HTML, CSS, and basic JavaScript.",
      totalPrice: 0,
      thumbnail: img1.src,
      rating: 4.2,
      ratingsCount: 12000,
      isBestSeller: true,
      updated: "July 2023",
      progress: 0,
      sections: [
         {
            id: "sec3",
            title: "HTML Basics",
            price: 0,
            lectures: [
               {
                  id: "lec3",
                  title: "Intro to HTML",
                  fileType: "pdf",
                  fileUrl: "https://example.com/html.pdf",
                  isWatched: false,
               },
            ],
         },
      ],
   },
   {
      id: "4",
      title: "Complete JavaScript Course 2023",
      instructor: "Quang",
      category: { id: "cat1", name: "Web Development" },
      description:
         "Master JavaScript with the most comprehensive course available, taught by John Smith.",
      totalPrice: 0,
      thumbnail: img1.src,
      rating: 4.8,
      ratingsCount: 42297,
      isBestSeller: true,
      updated: "July 2023",
      progress: 0,
      sections: [],
   },
   {
      id: "5",
      title: "Python for Data Science",
      instructor: "Quang",
      category: { id: "cat1", name: "Web Development" },
      description:
         "Learn Python and data analysis techniques with hands-on projects, taught by Jane Doe.",
      totalPrice: 79.99,
      thumbnail: img1.src,
      rating: 4.7,
      ratingsCount: 30500,
      isBestSeller: false,
      updated: "August 2023",
      progress: 0,
      sections: [],
   },
   {
      id: "6",
      title: "Typescript for Front End",
      instructor: "Quang",
      category: { id: "cat1", name: "Web Development" },
      description: "Learn TypeScript and its application in frontend development with React.",
      totalPrice: 79.99,
      thumbnail: img1.src,
      rating: 4.7,
      ratingsCount: 30500,
      isBestSeller: false,
      updated: "August 2023",
      progress: 0,
      sections: [],
   },
   {
      id: "7",
      title: "Spring Boot 3",
      instructor: "Quang",
      category: { id: "cat1", name: "Web Development" },
      description: "Build REST APIs and full-stack applications using Spring Boot 3.",
      totalPrice: 79.99,
      thumbnail: img1.src,
      rating: 4.7,
      ratingsCount: 30500,
      isBestSeller: false,
      updated: "August 2023",
      progress: 0,
      sections: [],
   },
   {
      id: "8",
      title: ".NET with C#",
      instructor: "Quang",
      category: { id: "cat1", name: "Web Development" },
      description:
         "Develop modern web applications using .NET and C# in this beginner-friendly course.",
      totalPrice: 79.99,
      thumbnail: img1.src,
      rating: 4.7,
      ratingsCount: 30500,
      isBestSeller: false,
      updated: "August 2023",
      progress: 0,
      sections: [],
   },
   {
      id: "9",
      title: "C",
      instructor: "Quang",
      category: { id: "cat1", name: "Web Development" },
      description:
         "Understand the fundamentals of programming in C language with practical examples.",
      totalPrice: 79.99,
      thumbnail: img1.src,
      rating: 4.7,
      ratingsCount: 30500,
      isBestSeller: false,
      updated: "August 2023",
      progress: 0,
      sections: [],
   },
];
